# Generated by Django 5.2.10 on 2026-08-05 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=50, unique=True)),
                ('kategori', models.CharField(choices=[('UMUM', 'Penugasan / Diskusi Umum'), ('PRODUKSI', 'Pesanan Produksi (Global)'), ('PRIVATE', 'Pesan Pribadi / Rahasia')], default='UMUM', max_length=15)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, help_text='Teks pembuka diskusi atau instruksi awal')),
                ('aturan_penyelesaian', models.CharField(choices=[('SALAH_SATU', 'Cukup Satu Anggota'), ('SEMUA', 'Semua Anggota Harus ACC'), ('PIC', 'Hanya Penanggung Jawab (PIC)')], default='SALAH_SATU', max_length=15)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('selesai', models.BooleanField(default=False)),
                ('catatan_selesai', models.TextField(blank=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='wo_dibuat', to=settings.AUTH_USER_MODEL)),
                ('diselesaikan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wo_diselesaikan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wo_work_order',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='DetailPesananProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(help_text='Varian Pigment (misal: Super White SC SC)', max_length=255)),
                ('unit', models.CharField(choices=[('PCS_1', 'Pcs (1 kg)'), ('GALON_5', 'Galon (5 kg)'), ('DUS_12', 'Dus (12 kg)'), ('PAIL_20', 'Pail (20 kg)'), ('PAIL_25', 'Pail (25 kg)'), ('PAIL_30', 'Pail (30 kg)')], max_length=10)),
                ('stiker', models.CharField(choices=[('POLOS', 'Polos (Tanpa Merek)'), ('PT', 'Stiker PT'), ('CV', 'Stiker CV')], max_length=10)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_produksi', to='work_order.workorder')),
            ],
            options={
                'db_table': 'wo_detail_produksi',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_chat', to='work_order.workorder')),
            ],
            options={
                'db_table': 'wo_pesan',
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pic', models.BooleanField(default=False)),
                ('is_selesai_personal', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan', to='work_order.workorder')),
            ],
            options={
                'db_table': 'wo_penugasan',
                'unique_together': {('work_order', 'staff')},
            },
        ),
    ]
