# Generated by Django 5.2.10 on 2026-08-07 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=7, unique=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'wo_counter',
            },
        ),
        migrations.AlterModelOptions(
            name='workorderpenugasan',
            options={'ordering': ['-is_pic', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='workorderpenugasan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workorderpenugasan',
            name='ditandai_pada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailpesananproduksi',
            name='nama_item',
            field=models.CharField(help_text='Varian Pigment (mis. Super White SC)', max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='kategori',
            field=models.CharField(choices=[('UMUM', 'Penugasan / Diskusi Umum'), ('PRODUKSI', 'Pesanan Produksi (Global)'), ('PRIVATE', 'Pesan Pribadi / Rahasia')], db_index=True, default='UMUM', max_length=15),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='selesai',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workorderpenugasan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_ditugaskan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderpesan',
            name='pengirim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wo_pesan_terkirim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['selesai', 'kategori', 'deadline'], name='ix_wo_papan'),
        ),
        migrations.AddIndex(
            model_name='workorderpesan',
            index=models.Index(fields=['work_order', 'dibuat_pada'], name='ix_wo_pesan_urut'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('selesai', False), ('waktu_selesai__isnull', False), _connector='OR'), name='ck_wo_selesai_berwaktu'),
        ),
        migrations.AddConstraint(
            model_name='workorderpenugasan',
            constraint=models.UniqueConstraint(fields=('work_order', 'staff'), name='uq_wo_penugasan'),
        ),
        migrations.AddConstraint(
            model_name='workorderpenugasan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pic', True)), fields=('work_order',), name='uq_wo_pic_tunggal'),
        ),
    ]
