# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
import dokumen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(choices=[('SURAT_JALAN', 'Surat jalan'), ('FAKTUR', 'Faktur suplier'), ('BUKTI_BAYAR', 'Bukti transfer'), ('FOTO_BARANG', 'Foto barang'), ('KONTRAK', 'Kontrak / perjanjian'), ('LAIN', 'Lain-lain')], db_index=True, max_length=16)),
                ('berkas', models.FileField(upload_to=dokumen.models.path_lampiran)),
                ('nama_asli', models.CharField(blank=True, max_length=255)),
                ('ukuran_byte', models.PositiveIntegerField(default=0, editable=False)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Lampiran',
                'db_table': 'dokumen_lampiran',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
