# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lampiran',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lampiran',
            name='digantikan_oleh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menggantikan', to='dokumen.lampiran'),
        ),
        migrations.AddIndex(
            model_name='lampiran',
            index=models.Index(fields=['content_type', 'object_id'], name='ix_lampiran_pemilik'),
        ),
        migrations.AddIndex(
            model_name='lampiran',
            index=models.Index(fields=['jenis', '-dibuat_pada'], name='ix_lampiran_jenis'),
        ),
    ]
