# Generated by Django 5.2.10 on 2026-08-21 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabangToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: JKT-01', max_length=20, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Pracindo Retail Jakarta', max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesiKasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_buka', models.DateTimeField(auto_now_add=True)),
                ('waktu_tutup', models.DateTimeField(blank=True, null=True)),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_penjualan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('AKTIF', 'Sedang Buka'), ('DITUTUP', 'Tutup & Disetor ke Pusat')], default='AKTIF', max_length=20)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.cabangtoko')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_struk', models.CharField(max_length=50, unique=True)),
                ('waktu_transaksi', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_bayar', models.CharField(choices=[('TUNAI', 'Tunai'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('BERHASIL', 'Berhasil'), ('RETUR', 'Retur')], default='BERHASIL', max_length=20)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='retail.sesikasir')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.transaksipos')),
            ],
        ),
        migrations.CreateModel(
            name='StokRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='Kuantitas fisik di toko')),
                ('harga_jual', models.DecimalField(decimal_places=2, help_text='Harga jual retail', max_digits=12)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='retail.cabangtoko')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.produk')),
            ],
            options={
                'unique_together': {('cabang', 'produk')},
            },
        ),
    ]
