# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import staff_user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('departemen', models.CharField(choices=[('GUDANG', 'Gudang'), ('AKUNTING', 'Akunting'), ('KEUANGAN', 'Keuangan'), ('PRODUKSI', 'Produksi'), ('PENJUALAN', 'Penjualan'), ('UMUM', 'Umum')], default='UMUM', max_length=12)),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jabatan',
                'db_table': 'staff_user_jabatan',
                'ordering': ['level', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nip', models.CharField(blank=True, help_text='Nomor induk pegawai. Dicantumkan di dokumen.', max_length=24, null=True, unique=True)),
                ('role', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin'), ('AKUNTING', 'Akunting'), ('KEUANGAN', 'Keuangan'), ('GUDANG', 'Gudang'), ('PRODUKSI', 'Produksi'), ('SALES', 'Sales'), ('STAFF', 'Staff')], db_index=True, default='STAFF', max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/%Y/%m/')),
                ('nomor_hp', models.CharField(blank=True, max_length=20)),
                ('status_kerja', models.CharField(choices=[('AKTIF', 'Aktif'), ('CUTI', 'Cuti'), ('KELUAR', 'Sudah keluar')], db_index=True, default='AKTIF', max_length=8)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
                ('disetujui_pada', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ditolak_pada', models.DateTimeField(blank=True, editable=False, null=True)),
                ('alasan_tolak', models.TextField(blank=True)),
                ('atasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bawahan', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='akun_disetujui', to=settings.AUTH_USER_MODEL)),
                ('entitas_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengguna_default', to='core.entitas')),
                ('entitas_diizinkan', models.ManyToManyField(blank=True, related_name='pengguna_diizinkan', to='core.entitas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemegang', to='staff_user.jabatan')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'db_table': 'staff_user_profil',
                'ordering': ['username'],
            },
            managers=[
                ('objects', staff_user.models.ProfilManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataKepegawaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nik_ktp', models.CharField(blank=True, max_length=16)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=80)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField(blank=True)),
                ('status_pajak', models.CharField(blank=True, choices=[('TK/0', 'TK/0 - Tidak kawin, tanpa tanggungan'), ('TK/1', 'TK/1'), ('TK/2', 'TK/2'), ('TK/3', 'TK/3'), ('K/0', 'K/0 - Kawin, tanpa tanggungan'), ('K/1', 'K/1'), ('K/2', 'K/2'), ('K/3', 'K/3')], max_length=4)),
                ('bank', models.CharField(blank=True, max_length=40)),
                ('no_rekening', models.CharField(blank=True, max_length=40)),
                ('nama_rekening', models.CharField(blank=True, max_length=120)),
                ('kontak_darurat_nama', models.CharField(blank=True, max_length=120)),
                ('kontak_darurat_hubungan', models.CharField(blank=True, max_length=40)),
                ('kontak_darurat_hp', models.CharField(blank=True, max_length=20)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kepegawaian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data kepegawaian',
                'verbose_name_plural': 'Data kepegawaian',
                'db_table': 'staff_user_data_kepegawaian',
            },
        ),
        migrations.CreateModel(
            name='RiwayatAkses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_dicoba', models.CharField(max_length=150)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('berhasil', models.BooleanField(db_index=True)),
                ('alasan_gagal', models.CharField(blank=True, max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_akses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Riwayat akses',
                'db_table': 'staff_user_riwayat_akses',
                'ordering': ['-waktu'],
            },
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['role', 'is_active'], name='ix_profil_role_aktif'),
        ),
        migrations.AddConstraint(
            model_name='profil',
            constraint=models.CheckConstraint(condition=models.Q(('tanggal_keluar__isnull', True), ('tanggal_masuk__isnull', True), ('tanggal_keluar__gte', models.F('tanggal_masuk')), _connector='OR'), name='ck_profil_tanggal_urut'),
        ),
        migrations.AddIndex(
            model_name='riwayatakses',
            index=models.Index(fields=['username_dicoba', '-waktu'], name='ix_akses_username'),
        ),
        migrations.AddIndex(
            model_name='riwayatakses',
            index=models.Index(fields=['berhasil', '-waktu'], name='ix_akses_hasil'),
        ),
    ]
