# Generated by Django 5.2.10 on 2026-08-01 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_seed_entitas'),
        ('staff_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('departemen', models.CharField(choices=[('GUDANG', 'Gudang'), ('AKUNTING', 'Akunting'), ('KEUANGAN', 'Keuangan'), ('PRODUKSI', 'Produksi'), ('PENJUALAN', 'Penjualan'), ('UMUM', 'Umum')], default='UMUM', max_length=12)),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jabatan',
                'db_table': 'staff_user_jabatan',
                'ordering': ['level', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatAkses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_dicoba', models.CharField(max_length=150)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('berhasil', models.BooleanField(db_index=True)),
                ('alasan_gagal', models.CharField(blank=True, max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Riwayat akses',
                'db_table': 'staff_user_riwayat_akses',
                'ordering': ['-waktu'],
            },
        ),
        migrations.AlterModelManagers(
            name='profil',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='alasan_tolak',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='atasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bawahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='akun_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='disetujui_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='ditolak_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='entitas_diizinkan',
            field=models.ManyToManyField(blank=True, related_name='pengguna_diizinkan', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='nip',
            field=models.CharField(blank=True, help_text='Nomor induk pegawai. Dicantumkan di dokumen.', max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='status_kerja',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('CUTI', 'Cuti'), ('KELUAR', 'Sudah keluar')], db_index=True, default='AKTIF', max_length=8),
        ),
        migrations.AddField(
            model_name='profil',
            name='tanggal_keluar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='entitas_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengguna_default', to='core.entitas'),
        ),
        migrations.CreateModel(
            name='DataKepegawaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nik_ktp', models.CharField(blank=True, max_length=16)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=80)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField(blank=True)),
                ('status_pajak', models.CharField(blank=True, choices=[('TK/0', 'TK/0 - Tidak kawin, tanpa tanggungan'), ('TK/1', 'TK/1'), ('TK/2', 'TK/2'), ('TK/3', 'TK/3'), ('K/0', 'K/0 - Kawin, tanpa tanggungan'), ('K/1', 'K/1'), ('K/2', 'K/2'), ('K/3', 'K/3')], max_length=4)),
                ('bank', models.CharField(blank=True, max_length=40)),
                ('no_rekening', models.CharField(blank=True, max_length=40)),
                ('nama_rekening', models.CharField(blank=True, max_length=120)),
                ('kontak_darurat_nama', models.CharField(blank=True, max_length=120)),
                ('kontak_darurat_hubungan', models.CharField(blank=True, max_length=40)),
                ('kontak_darurat_hp', models.CharField(blank=True, max_length=20)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kepegawaian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data kepegawaian',
                'verbose_name_plural': 'Data kepegawaian',
                'db_table': 'staff_user_data_kepegawaian',
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemegang', to='staff_user.jabatan'),
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['role', 'is_active'], name='ix_profil_role_aktif'),
        ),
        migrations.AddConstraint(
            model_name='profil',
            constraint=models.CheckConstraint(condition=models.Q(('tanggal_keluar__isnull', True), ('tanggal_masuk__isnull', True), ('tanggal_keluar__gte', models.F('tanggal_masuk')), _connector='OR'), name='ck_profil_tanggal_urut'),
        ),
        migrations.AddField(
            model_name='riwayatakses',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_akses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='riwayatakses',
            index=models.Index(fields=['username_dicoba', '-waktu'], name='ix_akses_username'),
        ),
        migrations.AddIndex(
            model_name='riwayatakses',
            index=models.Index(fields=['berhasil', '-waktu'], name='ix_akses_hasil'),
        ),
    ]
