# Generated by Django 5.2.10 on 2026-08-04 00:41

import staff_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0002_jabatan_riwayatakses_alter_profil_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profil',
            managers=[
                ('objects', staff_user.models.ProfilManager()),
            ],
        ),
    ]
