# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('jenis', models.CharField(choices=[('MIXING', 'Mixing (raw → tangki)'), ('BLENDING', 'Blending (WIP ± raw → tangki)')], default='MIXING', max_length=10)),
                ('nama_hasil', models.CharField(max_length=120)),
                ('waktu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_qty_input', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('total_nilai_input', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tekor_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai_susut', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('qty_hasil', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai_hasil', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('harga_masuk_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('harga_hasil_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Diposting'), ('VOID', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=8)),
                ('catatan', models.TextField(blank=True, default='')),
                ('posting_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Batch',
                'ordering': ['-waktu', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BatchInputRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('menghabiskan', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SekuensBatch',
            fields=[
                ('awalan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=6)),
                ('terakhir', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sekuens Batch',
            },
        ),
        migrations.CreateModel(
            name='Tangki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(blank=True, max_length=80)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='TransferWip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('menghabiskan', models.BooleanField(default=False)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
