# Generated by Django 5.2.10 on 2026-08-01 07:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_seed_entitas'),
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('versi', models.PositiveSmallIntegerField(default=1)),
                ('nama', models.CharField(blank=True, max_length=120)),
                ('hasil_per_batch', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('susut_wajar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('berlaku_sejak', models.DateField(default=django.utils.timezone.localdate)),
                ('aktif', models.BooleanField(default=True)),
                ('produk_jadi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resep', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Resep',
                'db_table': 'produksi_resep',
                'ordering': ['produk_jadi__kode', '-versi'],
            },
        ),
        migrations.CreateModel(
            name='ResepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dipakai_di_resep', to='master.produk')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='produksi.resep')),
            ],
            options={
                'db_table': 'produksi_resep_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SesiProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('qty_target', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('qty_hasil', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BERJALAN', 'Berjalan'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_produksi', to='core.grupbahan')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi', to='produksi.resep')),
                ('tangki_hasil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesi_hasil', to='inventory.tangki')),
            ],
            options={
                'verbose_name_plural': 'Sesi produksi',
                'db_table': 'produksi_sesi',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SesiInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_rencana', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('qty_aktual', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.produk')),
                ('tangki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.tangki')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input', to='produksi.sesiproduksi')),
            ],
            options={
                'db_table': 'produksi_sesi_input',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='resep',
            constraint=models.UniqueConstraint(fields=('produk_jadi', 'versi'), name='uq_resep_versi'),
        ),
        migrations.AddConstraint(
            model_name='resep',
            constraint=models.CheckConstraint(condition=models.Q(('hasil_per_batch__gt', 0)), name='ck_resep_hasil_positif'),
        ),
        migrations.AddConstraint(
            model_name='resep',
            constraint=models.CheckConstraint(condition=models.Q(('susut_wajar__gte', 0), ('susut_wajar__lt', 1)), name='ck_resep_susut_wajar'),
        ),
        migrations.AddConstraint(
            model_name='resepitem',
            constraint=models.UniqueConstraint(fields=('resep', 'bahan'), name='uq_resep_item_bahan'),
        ),
        migrations.AddConstraint(
            model_name='resepitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_resep_item_qty'),
        ),
        migrations.AddIndex(
            model_name='sesiproduksi',
            index=models.Index(fields=['grup_bahan', 'status', '-tanggal'], name='ix_sesi_grup_status'),
        ),
        migrations.AddConstraint(
            model_name='sesiproduksi',
            constraint=models.UniqueConstraint(fields=('grup_bahan', 'nomor'), name='uq_sesi_nomor'),
        ),
        migrations.AddConstraint(
            model_name='sesiproduksi',
            constraint=models.CheckConstraint(condition=models.Q(('qty_target__gt', 0)), name='ck_sesi_target_positif'),
        ),
        migrations.AddConstraint(
            model_name='sesiinput',
            constraint=models.UniqueConstraint(fields=('sesi', 'bahan'), name='uq_sesi_input_bahan'),
        ),
    ]
