# Generated by Django 5.2.10 on 2026-09-02 18:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tangki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(blank=True, default='', max_length=80)),
                ('kapasitas_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tangki',
                'db_table': 'produksi_tangki',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=48, unique=True)),
                ('jenis', models.CharField(choices=[('MIXING', 'Mixing (racik dari pool bersama)'), ('BLENDING', 'Blending (racik dari batch lain)')], max_length=10)),
                ('nama_hasil', models.CharField(max_length=120)),
                ('qty_hasil', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai_hasil', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('susut_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai_susut', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('waktu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tangki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_set', to='produksi.tangki')),
            ],
            options={
                'verbose_name_plural': 'Batch',
                'db_table': 'produksi_batch',
                'ordering': ['-waktu', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferWip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=20)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_sumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_keluar', to='produksi.batch')),
                ('batch_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_masuk', to='produksi.batch')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transfer WIP',
                'db_table': 'produksi_transfer_wip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BatchInputRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, max_digits=20)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_raw', to='produksi.batch')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Batch input raw',
                'db_table': 'produksi_batch_input_raw',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_input_raw_qty_positif'), models.UniqueConstraint(fields=('batch', 'produk'), name='uq_input_raw_per_batch_produk')],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tangki'], name='ix_batch_tangki'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['jenis'], name='ix_batch_jenis'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_hasil__gte', 0)), name='ck_batch_qty_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_hasil__gte', 0)), name='ck_batch_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('susut_kg__gte', 0)), name='ck_batch_susut_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_transfer_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.CheckConstraint(condition=models.Q(('batch_sumber', models.F('batch_tujuan')), _negated=True), name='ck_transfer_beda_batch'),
        ),
    ]
