# Generated by Django 5.2.10 on 2026-08-12 16:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_entitas'),
        ('inventory', '0002_kemasan_mutasistok_nilai_keluar_and_more'),
        ('master', '0003_alter_kategori_kode_alter_pelanggan_kode_and_more'),
        ('produksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPengukuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=32, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('satuan', models.CharField(blank=True, max_length=20)),
                ('tipe_nilai', models.CharField(choices=[('ANGKA', 'Angka'), ('TEKS', 'Teks'), ('BOOL', 'Ya/Tidak')], default='ANGKA', max_length=10)),
                ('nilai_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('nilai_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produksi_jenis_pengukuran',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='SesiCatatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('teks', models.TextField()),
            ],
            options={
                'db_table': 'produksi_sesi_catatan',
                'ordering': ['waktu', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SesiPengukuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahap', models.CharField(choices=[('PROSES', 'Proses'), ('UJI', 'Hasil uji')], default='PROSES', max_length=10)),
                ('nilai', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('nilai_teks', models.CharField(blank=True, max_length=255)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'produksi_sesi_pengukuran',
                'ordering': ['waktu', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='sesiinput',
            name='uq_sesi_input_bahan',
        ),
        migrations.AddField(
            model_name='sesiinput',
            name='nilai_aktual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='hasil_masuk_pool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='jenis_sesi',
            field=models.CharField(choices=[('PRODUKSI', 'Produksi Rutin'), ('RND', 'R&D / Percobaan')], db_index=True, default='PRODUKSI', max_length=10),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='kategori_kegagalan',
            field=models.CharField(blank=True, choices=[('PROSES', 'Kesalahan proses (suhu, waktu, pengaduk)'), ('BAHAN', 'Bahan tidak sesuai'), ('ALAT', 'Kerusakan alat'), ('UJI', 'Tidak lulus uji'), ('LAIN', 'Lain-lain')], max_length=15),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='nilai_hasil',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='nilai_input',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='nilai_kerugian',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sesiproduksi',
            name='produk_jadi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.produk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesiproduksi',
            name='resep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesi', to='produksi.resep'),
        ),
        migrations.AlterField(
            model_name='sesiproduksi',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('BERJALAN', 'Berjalan'), ('SELESAI', 'Selesai'), ('GAGAL', 'Gagal'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='sesiinput',
            constraint=models.UniqueConstraint(condition=models.Q(('tangki__isnull', False)), fields=('sesi', 'bahan', 'tangki'), name='uq_sesi_input_tangki'),
        ),
        migrations.AddConstraint(
            model_name='sesiinput',
            constraint=models.UniqueConstraint(condition=models.Q(('tangki__isnull', True)), fields=('sesi', 'bahan'), name='uq_sesi_input_rak'),
        ),
        migrations.AddConstraint(
            model_name='sesiinput',
            constraint=models.CheckConstraint(condition=models.Q(('qty_aktual__gte', 0)), name='ck_sesi_input_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='sesiproduksi',
            constraint=models.CheckConstraint(condition=models.Q(('jenis_sesi', 'RND'), ('resep__isnull', False), _connector='OR'), name='ck_sesi_rutin_wajib_resep'),
        ),
        migrations.AddField(
            model_name='sesicatatan',
            name='penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesicatatan',
            name='sesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_eksperimen', to='produksi.sesiproduksi'),
        ),
        migrations.AddField(
            model_name='sesipengukuran',
            name='dicatat_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesipengukuran',
            name='mengoreksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dikoreksi_oleh', to='produksi.sesipengukuran'),
        ),
        migrations.AddField(
            model_name='sesipengukuran',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produksi.jenispengukuran'),
        ),
        migrations.AddField(
            model_name='sesipengukuran',
            name='sesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengukuran', to='produksi.sesiproduksi'),
        ),
        migrations.AddIndex(
            model_name='sesipengukuran',
            index=models.Index(fields=['sesi', 'nama', 'waktu'], name='ix_ukur_sesi_jenis'),
        ),
    ]
