# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('master', '0001_initial'),
        ('produksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='batch',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_diposting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchinputraw',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_raw', to='produksi.batch'),
        ),
        migrations.AddField(
            model_name='batchinputraw',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dipakai_produksi', to='master.produk'),
        ),
        migrations.AddConstraint(
            model_name='tangki',
            constraint=models.CheckConstraint(condition=models.Q(('kode', django.db.models.functions.text.Upper('kode'))), name='produksi_tangki_kode_uppercase'),
        ),
        migrations.AddField(
            model_name='batch',
            name='tangki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_set', to='produksi.tangki'),
        ),
        migrations.AddField(
            model_name='transferwip',
            name='batch_sumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keluar_wip', to='produksi.batch'),
        ),
        migrations.AddField(
            model_name='transferwip',
            name='batch_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_wip', to='produksi.batch'),
        ),
        migrations.AddConstraint(
            model_name='batchinputraw',
            constraint=models.UniqueConstraint(fields=('batch', 'produk'), name='produksi_produk_unik_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchinputraw',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='produksi_input_raw_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='batchinputraw',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='produksi_input_raw_nilai_non_negatif'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tangki', 'status', 'waktu'], name='prod_batch_tangki_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'waktu'], name='prod_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('qty_hasil__gt', 0), _connector='OR'), name='produksi_batch_posted_hasil_positif'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('tekor_kg__gte', 0)), name='produksi_batch_tekor_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_susut__gte', 0)), name='produksi_batch_susut_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('total_nilai_input', django.db.models.expressions.CombinedExpression(models.F('nilai_hasil'), '+', models.F('nilai_susut'))), _connector='OR'), name='produksi_batch_p1_konservasi_nilai'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('total_qty_input', django.db.models.expressions.CombinedExpression(models.F('qty_hasil'), '+', models.F('tekor_kg'))), _connector='OR'), name='produksi_batch_p2_konservasi_massa'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'POSTED'), _negated=True), ('posted_at__isnull', False), _connector='OR'), name='produksi_batch_posted_ada_jejak'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.UniqueConstraint(fields=('batch_tujuan', 'batch_sumber'), name='produksi_sumber_unik_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.CheckConstraint(condition=models.Q(('batch_tujuan', models.F('batch_sumber')), _negated=True), name='produksi_tidak_transfer_ke_diri_sendiri'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='produksi_input_wip_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='transferwip',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='produksi_input_wip_nilai_non_negatif'),
        ),
    ]
