# Generated by Django 5.2.10 on 2026-08-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_kategori_kode_alter_pelanggan_kode_and_more'),
        ('produksi', '0002_jenispengukuran_sesicatatan_sesipengukuran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.produk')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='komponen_hasil', to='produksi.sesiproduksi')),
                ('sesi_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='komponen_hasil', to='produksi.sesiinput')),
            ],
            options={
                'db_table': 'produksi_hasil_komponen',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('sesi', 'sesi_input'), name='uq_hasil_komponen_sesi_input'), models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='ck_hasil_komponen_qty_nonneg'), models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_hasil_komponen_nilai_nonneg')],
            },
        ),
    ]
