# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakturPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(choices=[('BARANG', 'Pembelian barang'), ('JASA', 'Jasa / beban')], default='BARANG', max_length=8)),
                ('no_internal', models.CharField(editable=False, max_length=32)),
                ('nomor_faktur', models.CharField(max_length=64)),
                ('tanggal_faktur', models.DateField()),
                ('termin_hari', models.PositiveSmallIntegerField(default=0)),
                ('tanggal_jatuh_tempo', models.DateField(db_index=True, editable=False)),
                ('total_tagihan', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('sisa_hutang', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('status', models.CharField(choices=[('BELUM_BAYAR', 'Belum dibayar'), ('SEBAGIAN', 'Dibayar sebagian'), ('LUNAS', 'Lunas'), ('BATAL', 'Dibatalkan')], db_index=True, default='BELUM_BAYAR', max_length=12)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Faktur pembelian',
                'db_table': 'akunting_faktur_pembelian',
                'ordering': ['tanggal_jatuh_tempo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FakturPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('no_internal', models.CharField(editable=False, max_length=32)),
                ('nomor_faktur', models.CharField(max_length=64, unique=True)),
                ('tanggal_faktur', models.DateField(default=django.utils.timezone.localdate)),
                ('termin_hari', models.PositiveSmallIntegerField(default=0)),
                ('tanggal_jatuh_tempo', models.DateField(db_index=True, editable=False)),
                ('total_tagihan', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('sisa_piutang', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('status', models.CharField(choices=[('BELUM_BAYAR', 'Belum dibayar'), ('SEBAGIAN', 'Dibayar sebagian'), ('LUNAS', 'Lunas'), ('BATAL', 'Dibatalkan')], db_index=True, default='BELUM_BAYAR', max_length=12)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Faktur Penjualan',
                'db_table': 'akunting_faktur_penjualan',
                'ordering': ['tanggal_jatuh_tempo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'akunting_jurnal_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JurnalUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True)),
                ('kejadian', models.CharField(choices=[('AUDIT_GUDANG', 'Penerimaan barang'), ('FAKTUR_MASUK', 'Faktur pembelian masuk'), ('SELISIH_HARGA', 'Selisih harga faktur'), ('BAYAR_HUTANG', 'Pembayaran hutang'), ('RETUR_BELI', 'Retur pembelian'), ('PENJUALAN', 'Penjualan'), ('TERIMA_PIUTANG', 'Penerimaan piutang'), ('BEBAN_KAS', 'Beban dibayar tunai'), ('PENYUSUTAN', 'Penyusutan aset tetap'), ('PRODUKSI', 'Rekonsiliasi sesi produksi'), ('KOREKSI', 'Jurnal balik / koreksi')], db_index=True, max_length=16)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(editable=False, max_length=96, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Jurnal umum',
                'db_table': 'akunting_jurnal_umum',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KartuHutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jenis', models.CharField(choices=[('FAKTUR', 'Faktur diterbitkan'), ('BAYAR', 'Pembayaran'), ('RETUR', 'Retur pembelian'), ('KOREKSI', 'Koreksi / pembatalan')], max_length=8)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kartu hutang',
                'db_table': 'akunting_kartu_hutang',
                'ordering': ['tanggal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KartuPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jenis', models.CharField(choices=[('FAKTUR', 'Faktur diterbitkan'), ('TERIMA', 'Pembayaran diterima'), ('RETUR', 'Retur penjualan'), ('KOREKSI', 'Koreksi / pembatalan')], max_length=8)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kartu Piutang',
                'db_table': 'akunting_kartu_piutang',
                'ordering': ['tanggal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PengeluaranKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor_bukti', models.CharField(editable=False, max_length=32, unique=True)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('pemohon', models.CharField(help_text='Nama staf yang meminta dana/melakukan pembelian', max_length=120)),
                ('keterangan', models.CharField(max_length=255)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Terposting (Lunas)'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Pengeluaran kas',
                'db_table': 'akunting_pengeluaran_kas',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('no_po', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TERKIRIM', 'Terkirim ke suplier'), ('DISETUJUI', 'Disetujui suplier'), ('DITOLAK', 'Ditolak suplier'), ('SEBAGIAN', 'Diterima sebagian'), ('SELESAI', 'Diterima penuh'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
                ('tanggal_kirim_diminta', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('ppn_persen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Persentase PPN (contoh: 11.00 untuk 11%). Isi 0 jika non-PKP.', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Purchase order',
                'db_table': 'akunting_purchase_order',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=200)),
                ('satuan', models.CharField(default='kg', max_length=8)),
                ('qty_pesan', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('qty_diterima', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
            ],
            options={
                'db_table': 'akunting_purchase_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoAkunBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('saldo_akhir', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'db_table': 'akunting_saldo_akun_bulanan',
                'ordering': ['-tahun', '-bulan', 'akun__kode'],
            },
        ),
        migrations.CreateModel(
            name='UangMukaSuplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sisa', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('referensi', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Uang muka suplier',
                'db_table': 'akunting_uang_muka_suplier',
                'ordering': ['tanggal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=8, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('tipe', models.CharField(choices=[('ASET', 'Aset'), ('KEWAJIBAN', 'Kewajiban'), ('EKUITAS', 'Ekuitas'), ('PENDAPATAN', 'Pendapatan'), ('BEBAN', 'Beban')], db_index=True, max_length=12)),
                ('boleh_diposting', models.BooleanField(default=True)),
                ('aktif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anak', to='akunting.akun')),
            ],
            options={
                'verbose_name_plural': 'Akun',
                'db_table': 'akunting_akun',
                'ordering': ['kode'],
            },
        ),
    ]
