# Generated by Django 5.2.10 on 2026-09-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0001_initial'),
        ('core', '0002_initial'),
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturpembelian',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran'),
        ),
        migrations.AddField(
            model_name='fakturpembelian',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_pembelian', to='core.entitas'),
        ),
    ]
