# Generated by Django 5.2.10 on 2026-09-02 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0002_initial'),
        ('core', '0002_initial'),
        ('dokumen', '0001_initial'),
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturpembelian',
            name='penerimaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faktur', to='warehouse.penerimaanbarang'),
        ),
        migrations.AddField(
            model_name='fakturpembelian',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_pembelian', to='master.suplier'),
        ),
        migrations.AddField(
            model_name='fakturpenjualan',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fakturpenjualan',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_penjualan', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='fakturpenjualan',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_penjualan', to='master.pelanggan'),
        ),
        migrations.AddField(
            model_name='jurnaldetail',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baris_jurnal', to='akunting.akun'),
        ),
        migrations.AddField(
            model_name='jurnalumum',
            name='dibalik_oleh',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membalik', to='akunting.jurnalumum'),
        ),
        migrations.AddField(
            model_name='jurnalumum',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurnalumum',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='jurnaldetail',
            name='jurnal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baris', to='akunting.jurnalumum'),
        ),
        migrations.AddField(
            model_name='kartuhutang',
            name='faktur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi', to='akunting.fakturpembelian'),
        ),
        migrations.AddField(
            model_name='kartupiutang',
            name='faktur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi', to='akunting.fakturpenjualan'),
        ),
        migrations.AddField(
            model_name='pembeliankemasan',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembeliankemasan',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas'),
        ),
        migrations.AddField(
            model_name='pembeliankemasan',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.kemasan'),
        ),
        migrations.AddField(
            model_name='pengeluarankas',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengeluarankas',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran'),
        ),
        migrations.AddField(
            model_name='pengeluarankas',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='pengeluarankas',
            name='kategori_beban',
            field=models.ForeignKey(limit_choices_to={'boleh_diposting': True, 'tipe': 'BEBAN'}, on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran_beban', to='akunting.akun'),
        ),
        migrations.AddField(
            model_name='pengeluarankas',
            name='sumber_dana',
            field=models.ForeignKey(limit_choices_to={'boleh_diposting': True, 'tipe': 'ASET'}, on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran_sumber', to='akunting.akun'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='master.suplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.produk'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='akunting.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderkemasanitem',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.kemasan'),
        ),
        migrations.AddField(
            model_name='purchaseorderkemasanitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='akunting.pembeliankemasan'),
        ),
        migrations.AddField(
            model_name='saldoakunbulanan',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_bulanan', to='akunting.akun'),
        ),
        migrations.AddField(
            model_name='saldoakunbulanan',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas'),
        ),
        migrations.AddField(
            model_name='uangmukasuplier',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas'),
        ),
        migrations.AddField(
            model_name='uangmukasuplier',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uang_muka', to='master.suplier'),
        ),
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['tipe', 'kode'], name='ix_akun_tipe_kode'),
        ),
        migrations.AddIndex(
            model_name='fakturpembelian',
            index=models.Index(fields=['suplier', 'status', 'tanggal_jatuh_tempo'], name='ix_faktur_sup_status_tempo'),
        ),
        migrations.AddIndex(
            model_name='fakturpembelian',
            index=models.Index(fields=['entitas', 'status'], name='ix_faktur_ent_status'),
        ),
        migrations.AddConstraint(
            model_name='fakturpembelian',
            constraint=models.UniqueConstraint(fields=('suplier', 'nomor_faktur'), name='uq_faktur_suplier_nomor'),
        ),
        migrations.AddConstraint(
            model_name='fakturpembelian',
            constraint=models.UniqueConstraint(fields=('entitas', 'no_internal'), name='uq_faktur_no_internal'),
        ),
        migrations.AddConstraint(
            model_name='fakturpembelian',
            constraint=models.CheckConstraint(condition=models.Q(('sisa_hutang__gte', 0)), name='ck_faktur_sisa_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fakturpembelian',
            constraint=models.CheckConstraint(condition=models.Q(('total_dibayar__gte', 0), ('total_dibayar__lte', models.F('total_tagihan'))), name='ck_faktur_dibayar_dalam_batas'),
        ),
        migrations.AddConstraint(
            model_name='fakturpembelian',
            constraint=models.CheckConstraint(condition=models.Q(('jenis', 'JASA'), ('penerimaan__isnull', False), _connector='OR'), name='ck_faktur_barang_wajib_penerimaan'),
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.UniqueConstraint(fields=('entitas', 'no_internal'), name='uq_fakturjual_no_internal'),
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.CheckConstraint(condition=models.Q(('sisa_piutang__gte', 0)), name='ck_fakturjual_sisa_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.CheckConstraint(condition=models.Q(('total_dibayar__gte', 0), ('total_dibayar__lte', models.F('total_tagihan'))), name='ck_fakturjual_dibayar_dalam_batas'),
        ),
        migrations.AddIndex(
            model_name='jurnalumum',
            index=models.Index(fields=['entitas', 'tanggal'], name='ix_jurnal_ent_tgl'),
        ),
        migrations.AddIndex(
            model_name='jurnalumum',
            index=models.Index(fields=['referensi'], name='ix_jurnal_referensi'),
        ),
        migrations.AddConstraint(
            model_name='jurnalumum',
            constraint=models.UniqueConstraint(fields=('entitas', 'nomor'), name='uq_jurnal_nomor_per_entitas'),
        ),
        migrations.AddIndex(
            model_name='jurnaldetail',
            index=models.Index(fields=['akun', 'jurnal'], name='ix_jd_akun_jurnal'),
        ),
        migrations.AddConstraint(
            model_name='jurnaldetail',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_jd_nilai_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='jurnaldetail',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_jd_satu_sisi'),
        ),
        migrations.AddConstraint(
            model_name='jurnaldetail',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _negated=True), name='ck_jd_tidak_nol_dua_duanya'),
        ),
        migrations.AddIndex(
            model_name='kartuhutang',
            index=models.Index(fields=['faktur', 'tanggal'], name='ix_kh_faktur_tgl'),
        ),
        migrations.AddConstraint(
            model_name='kartuhutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_kh_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='kartuhutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_kh_satu_sisi'),
        ),
        migrations.AddIndex(
            model_name='kartupiutang',
            index=models.Index(fields=['faktur', 'tanggal'], name='ix_kp_faktur_tgl'),
        ),
        migrations.AddConstraint(
            model_name='kartupiutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_kp_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='kartupiutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_kp_satu_sisi'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['entitas', 'status', '-tanggal'], name='ix_po_ent_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['suplier', 'status'], name='ix_po_sup_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('entitas', 'no_po'), name='uq_po_nomor_per_entitas'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order'], name='ix_poitem_po'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_pesan__gt', 0)), name='ck_poitem_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('harga_per_kg__gte', 0)), name='ck_poitem_harga_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diterima__gte', 0), ('qty_diterima__lte', models.F('qty_pesan'))), name='ck_poitem_terima_dalam_batas'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'produk'), name='uq_poitem_produk'),
        ),
        migrations.AddIndex(
            model_name='saldoakunbulanan',
            index=models.Index(fields=['entitas', 'tahun', 'bulan'], name='ix_saldo_ent_periode'),
        ),
        migrations.AddConstraint(
            model_name='saldoakunbulanan',
            constraint=models.UniqueConstraint(fields=('akun', 'entitas', 'tahun', 'bulan'), name='uq_saldo_akun_periode'),
        ),
        migrations.AddConstraint(
            model_name='saldoakunbulanan',
            constraint=models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_saldo_bulan_valid'),
        ),
        migrations.AddIndex(
            model_name='uangmukasuplier',
            index=models.Index(fields=['suplier', 'entitas'], name='ix_um_sup_ent'),
        ),
        migrations.AddConstraint(
            model_name='uangmukasuplier',
            constraint=models.CheckConstraint(condition=models.Q(('sisa__gte', 0), ('sisa__lte', models.F('nominal'))), name='ck_um_sisa_dalam_batas'),
        ),
    ]
