# Generated by Django 5.2.10 on 2026-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunting', '0005_seed_coa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TERKIRIM', 'Terkirim ke suplier'), ('DISETUJUI', 'Disetujui suplier'), ('DITOLAK', 'Ditolak suplier'), ('SEBAGIAN', 'Diterima sebagian'), ('SELESAI', 'Diterima penuh'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
