# Generated by Django 5.2.10 on 2026-08-06 01:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunting', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ppn_persen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Persentase PPN (contoh: 11.00 untuk 11%). Isi 0 jika non-PKP.', max_digits=5),
        ),
    ]
