# Generated by Django 5.2.10 on 2026-08-09 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunting', '0007_purchaseorder_ppn_persen'),
        ('core', '0003_seed_entitas'),
        ('master', '0003_alter_kategori_kode_alter_pelanggan_kode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('no_internal', models.CharField(editable=False, max_length=32)),
                ('nomor_faktur', models.CharField(max_length=64, unique=True)),
                ('tanggal_faktur', models.DateField(default=django.utils.timezone.localdate)),
                ('termin_hari', models.PositiveSmallIntegerField(default=0)),
                ('tanggal_jatuh_tempo', models.DateField(db_index=True, editable=False)),
                ('total_tagihan', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('sisa_piutang', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('status', models.CharField(choices=[('BELUM_BAYAR', 'Belum dibayar'), ('SEBAGIAN', 'Dibayar sebagian'), ('LUNAS', 'Lunas'), ('BATAL', 'Dibatalkan')], db_index=True, default='BELUM_BAYAR', max_length=12)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_penjualan', to='core.entitas')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur_penjualan', to='master.pelanggan')),
            ],
            options={
                'verbose_name_plural': 'Faktur Penjualan',
                'db_table': 'akunting_faktur_penjualan',
                'ordering': ['tanggal_jatuh_tempo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KartuPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jenis', models.CharField(choices=[('FAKTUR', 'Faktur diterbitkan'), ('TERIMA', 'Pembayaran diterima'), ('RETUR', 'Retur penjualan'), ('KOREKSI', 'Koreksi / pembatalan')], max_length=8)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi', to='akunting.fakturpenjualan')),
            ],
            options={
                'verbose_name_plural': 'Kartu Piutang',
                'db_table': 'akunting_kartu_piutang',
                'ordering': ['tanggal', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.UniqueConstraint(fields=('entitas', 'no_internal'), name='uq_fakturjual_no_internal'),
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.CheckConstraint(condition=models.Q(('sisa_piutang__gte', 0)), name='ck_fakturjual_sisa_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fakturpenjualan',
            constraint=models.CheckConstraint(condition=models.Q(('total_dibayar__gte', 0), ('total_dibayar__lte', models.F('total_tagihan'))), name='ck_fakturjual_dibayar_dalam_batas'),
        ),
        migrations.AddIndex(
            model_name='kartupiutang',
            index=models.Index(fields=['faktur', 'tanggal'], name='ix_kp_faktur_tgl'),
        ),
        migrations.AddConstraint(
            model_name='kartupiutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_kp_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='kartupiutang',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_kp_satu_sisi'),
        ),
    ]
