# Generated by Django 5.2.10 on 2026-08-09 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunting', '0008_fakturpenjualan_kartupiutang_and_more'),
        ('core', '0003_seed_entitas'),
        ('dokumen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengeluaranKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor_bukti', models.CharField(editable=False, max_length=32, unique=True)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('pemohon', models.CharField(help_text='Nama staf yang meminta dana/melakukan pembelian', max_length=120)),
                ('keterangan', models.CharField(max_length=255)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Terposting (Lunas)'), ('BATAL', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran')),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran', to='core.entitas')),
                ('kategori_beban', models.ForeignKey(limit_choices_to={'boleh_diposting': True, 'tipe': 'BEBAN'}, on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran_beban', to='akunting.akun')),
                ('sumber_dana', models.ForeignKey(limit_choices_to={'boleh_diposting': True, 'tipe': 'ASET'}, on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran_sumber', to='akunting.akun')),
            ],
            options={
                'verbose_name_plural': 'Pengeluaran kas',
                'db_table': 'akunting_pengeluaran_kas',
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
