# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=8, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('jenis', models.CharField(choices=[('BADAN_HUKUM', 'Badan hukum'), ('PERORANGAN', 'Perorangan')], max_length=12)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Entitas',
                'db_table': 'core_entitas',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='GrupBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Grup bahan',
                'db_table': 'core_grup_bahan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeAkuntansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('ditutup', models.BooleanField(db_index=True, default=False)),
                ('ditutup_pada', models.DateTimeField(blank=True, editable=False, null=True)),
                ('alasan_buka', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Periode akuntansi',
                'db_table': 'core_periode_akuntansi',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
        migrations.CreateModel(
            name='CounterDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=16)),
                ('periode', models.CharField(max_length=6)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'Counter dokumen',
                'db_table': 'core_counter_dokumen',
                'ordering': ['entitas', 'jenis', '-periode'],
            },
        ),
        migrations.AddField(
            model_name='entitas',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitas', to='core.grupbahan'),
        ),
    ]
