# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeakuntansi',
            name='ditutup_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodeakuntansi',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periode', to='core.entitas'),
        ),
        migrations.AddConstraint(
            model_name='counterdokumen',
            constraint=models.UniqueConstraint(fields=('entitas', 'jenis', 'periode'), name='uq_counter_dokumen'),
        ),
        migrations.AddIndex(
            model_name='periodeakuntansi',
            index=models.Index(fields=['entitas', 'tahun', 'bulan', 'ditutup'], name='ix_periode_lookup'),
        ),
        migrations.AddConstraint(
            model_name='periodeakuntansi',
            constraint=models.UniqueConstraint(fields=('entitas', 'tahun', 'bulan'), name='uq_periode_entitas'),
        ),
        migrations.AddConstraint(
            model_name='periodeakuntansi',
            constraint=models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_periode_bulan_valid'),
        ),
    ]
