# Generated by Django 5.2.10 on 2026-08-03 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_seed_entitas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JejakAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aksi', models.CharField(choices=[('BUAT', 'Dibuat'), ('UBAH', 'Diubah'), ('KIRIM', 'Dikirim'), ('BATAL', 'Dibatalkan'), ('SETUJU', 'Disetujui'), ('TOLAK', 'Ditolak'), ('SELESAI', 'Diselesaikan'), ('TUTUP', 'Ditutup'), ('BUKA', 'Dibuka kembali'), ('NONAKTIF', 'Dinonaktifkan'), ('AKTIF', 'Diaktifkan'), ('UBAH_ROLE', 'Peran diubah'), ('RESET_PWD', 'Password direset')], db_index=True, max_length=12)),
                ('object_id', models.PositiveBigIntegerField()),
                ('label_objek', models.CharField(blank=True, max_length=120)),
                ('status_lama', models.CharField(blank=True, max_length=32)),
                ('status_baru', models.CharField(blank=True, max_length=32)),
                ('alasan', models.TextField(blank=True)),
                ('rincian', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jejak_aktivitas', to='core.entitas')),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jejak_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jejak aktivitas',
                'verbose_name_plural': 'Jejak aktivitas',
                'db_table': 'audit_jejak_aktivitas',
                'ordering': ['-waktu', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ix_jejak_objek'), models.Index(fields=['oleh', '-waktu'], name='ix_jejak_oleh'), models.Index(fields=['entitas', '-waktu'], name='ix_jejak_entitas'), models.Index(fields=['aksi', '-waktu'], name='ix_jejak_aksi')],
            },
        ),
    ]
