# Generated by Django 5.2.10 on 2026-08-01 01:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0002_initial'),
        ('core', '0002_initial'),
        ('dokumen', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenerimaanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('no_surat_jalan', models.CharField(max_length=64)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penerimaan', to='akunting.purchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Penerimaan barang',
                'db_table': 'warehouse_penerimaan_barang',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PenerimaanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_diterima', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_ditolak', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('alasan_tolak', models.CharField(blank=True, max_length=255)),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='warehouse.penerimaanbarang')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisasi', to='akunting.purchaseorderitem')),
            ],
            options={
                'db_table': 'warehouse_penerimaan_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('qty_curah', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_kemasan', models.PositiveIntegerField()),
                ('isi_per_kemasan', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupbahan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Packaging',
                'db_table': 'warehouse_packaging',
                'ordering': ['-tanggal', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_curah__gt', 0)), name='ck_packaging_curah')],
            },
        ),
        migrations.AddIndex(
            model_name='penerimaanbarang',
            index=models.Index(fields=['tanggal'], name='ix_penerimaan_tanggal'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanbarang',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'no_surat_jalan'), name='uq_penerimaan_surat_jalan'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diterima__gte', 0), ('qty_ditolak__gte', 0)), name='ck_penerimaan_item_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diterima', 0), ('qty_ditolak', 0), _negated=True), name='ck_penerimaan_item_tidak_nol'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.UniqueConstraint(fields=('penerimaan', 'po_item'), name='uq_penerimaan_item'),
        ),
    ]
