# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0001_initial'),
        ('core', '0001_initial'),
        ('dokumen', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_do', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('pengemudi', models.CharField(blank=True, max_length=100)),
                ('plat_nomor', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'tx_delivery_order',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='warehouse.deliveryorder')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.produk')),
            ],
            options={
                'db_table': 'tx_delivery_order_item',
            },
        ),
        migrations.CreateModel(
            name='PenerimaanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('no_surat_jalan', models.CharField(max_length=64)),
                ('ada_selisih', models.BooleanField(db_index=True, default=False, editable=False)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penerimaan', to='akunting.purchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Penerimaan barang',
                'db_table': 'warehouse_penerimaan_barang',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PenerimaanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kemasan', models.CharField(choices=[('KARUNG', 'Karung'), ('DRUM', 'Drum'), ('JERIGEN', 'Jerigen'), ('DUS', 'Dus'), ('SAK', 'Sak'), ('CURAH', 'Curah / tanpa kemasan')], default='CURAH', max_length=8)),
                ('jumlah_koli', models.PositiveIntegerField(blank=True, help_text='Jumlah karung/drum/dus. Kosongkan untuk curah.', null=True)),
                ('isi_per_koli', models.DecimalField(blank=True, decimal_places=3, help_text='Isi nominal tiap koli menurut label.', max_digits=14, null=True)),
                ('qty_deklarasi', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('qty_diterima', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('qty_ditolak', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('alasan_tolak', models.CharField(blank=True, max_length=255)),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='warehouse.penerimaanbarang')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisasi', to='akunting.purchaseorderitem')),
            ],
            options={
                'db_table': 'warehouse_penerimaan_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LaporanSelisih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('jenis', models.CharField(choices=[('KURANG_KIRIM', 'Kurang kirim'), ('LEBIH_KIRIM', 'Lebih kirim'), ('BERAT_KURANG', 'Berat kurang dari label'), ('RUSAK', 'Barang rusak'), ('SALAH_BARANG', 'Barang tidak sesuai pesanan'), ('MUTU', 'Mutu tidak sesuai')], db_index=True, max_length=14)),
                ('status', models.CharField(choices=[('DIBUKA', 'Dibuka'), ('DIAJUKAN', 'Diajukan ke suplier'), ('DISEPAKATI', 'Disepakati suplier'), ('DISELESAIKAN', 'Selesai'), ('DITUTUP', 'Ditutup tanpa klaim')], db_index=True, default='DIBUKA', max_length=14)),
                ('qty_selisih', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('nilai_selisih', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('uraian', models.TextField()),
                ('resolusi', models.CharField(blank=True, choices=[('TERIMA', 'Terima apa adanya'), ('POTONG', 'Potong tagihan'), ('SUSULAN', 'Suplier kirim susulan'), ('RETUR', 'Retur ke suplier'), ('GANTI', 'Ganti barang')], max_length=8)),
                ('nilai_klaim', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('catatan_resolusi', models.TextField(blank=True)),
                ('diselesaikan_pada', models.DateTimeField(blank=True, editable=False, null=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diselesaikan_oleh', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selisih_diselesaikan', to=settings.AUTH_USER_MODEL)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran')),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_selisih', to='warehouse.penerimaanbarang')),
                ('penerimaan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laporan_selisih', to='warehouse.penerimaanitem')),
            ],
            options={
                'verbose_name_plural': 'Laporan selisih',
                'db_table': 'warehouse_laporan_selisih',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('qty_curah', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_kemasan', models.PositiveIntegerField()),
                ('isi_per_kemasan', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupbahan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Packaging',
                'db_table': 'warehouse_packaging',
                'ordering': ['-tanggal', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_curah__gt', 0)), name='ck_packaging_curah')],
            },
        ),
        migrations.AddIndex(
            model_name='penerimaanbarang',
            index=models.Index(fields=['tanggal'], name='ix_penerimaan_tanggal'),
        ),
        migrations.AddIndex(
            model_name='penerimaanbarang',
            index=models.Index(fields=['ada_selisih'], name='ix_penerimaan_selisih'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanbarang',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'no_surat_jalan'), name='uq_penerimaan_surat_jalan'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diterima__gte', 0), ('qty_ditolak__gte', 0)), name='ck_penerimaan_item_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_diterima', 0), ('qty_ditolak', 0), _negated=True), name='ck_penerimaan_item_tidak_nol'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('isi_per_koli__isnull', True), ('isi_per_koli__gt', 0), _connector='OR'), name='ck_penerimaan_isi_positif'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.UniqueConstraint(fields=('penerimaan', 'po_item'), name='uq_penerimaan_item'),
        ),
        migrations.AddIndex(
            model_name='laporanselisih',
            index=models.Index(fields=['status', '-tanggal'], name='ix_selisih_status'),
        ),
        migrations.AddConstraint(
            model_name='laporanselisih',
            constraint=models.UniqueConstraint(fields=('nomor',), name='uq_selisih_nomor'),
        ),
        migrations.AddConstraint(
            model_name='laporanselisih',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_klaim__gte', 0)), name='ck_selisih_klaim_nonneg'),
        ),
    ]
