# Generated by Django 5.2.10 on 2026-09-04 16:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('master', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='produk',
        ),
        migrations.AddField(
            model_name='packaging',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='master.masterproduk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penerimaanitem',
            name='jenis_kemasan',
            field=models.CharField(choices=[('KARUNG', 'Karung'), ('DRUM', 'Drum'), ('JERIGEN', 'Jerigen'), ('DUS', 'Dus'), ('SAK', 'Sak'), ('BAG', 'Bag'), ('CURAH', 'Curah / tanpa kemasan')], default='CURAH', max_length=8),
        ),
        migrations.CreateModel(
            name='MutasiStokBarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemasan', models.IntegerField(choices=[(1, 'PCS@1KG'), (2, 'GALON@5KG'), (3, 'DUS@12KG'), (4, 'PAIL@10KG'), (5, 'PAIL@15KG'), (6, 'PAIL@20KG'), (7, 'PAIL@25KG'), (8, 'PAIL@30KG')])),
                ('tipe', models.CharField(choices=[('PRODUKSI', 'Masuk dari produksi (packing)'), ('DISTRIBUSI', 'Keluar untuk distribusi'), ('RETUR', 'Retur masuk dari distribusi'), ('PENYESUAIAN', 'Penyesuaian manual')], max_length=14)),
                ('arah', models.SmallIntegerField()),
                ('qty_unit', models.IntegerField()),
                ('netto_per_unit_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('waktu', models.DateTimeField(db_index=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_stok_jadi', to='core.entitas')),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_stok_jadi', to='core.grupbahan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_stok_jadi', to='master.masterproduk')),
            ],
            options={
                'verbose_name_plural': 'Mutasi stok barang jadi',
                'db_table': 'inventory_mutasi_stok_jadi',
                'ordering': ['waktu', 'id'],
                'indexes': [models.Index(fields=['entitas', 'item', 'kemasan', 'waktu'], name='ix_mutasi_stok_posisi')],
                'constraints': [models.UniqueConstraint(fields=('ref_type', 'ref_id', 'tipe', 'entitas'), name='uq_mutasi_stok_idempoten'), models.CheckConstraint(condition=models.Q(('arah__in', [-1, 1])), name='ck_mutasi_stok_arah_valid'), models.CheckConstraint(condition=models.Q(('qty_unit__gt', 0)), name='ck_mutasi_stok_unit_positif'), models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_mutasi_stok_kg_positif')],
            },
        ),
        migrations.CreateModel(
            name='StokBarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kemasan', models.IntegerField(choices=[(1, 'PCS@1KG'), (2, 'GALON@5KG'), (3, 'DUS@12KG'), (4, 'PAIL@10KG'), (5, 'PAIL@15KG'), (6, 'PAIL@20KG'), (7, 'PAIL@25KG'), (8, 'PAIL@30KG')])),
                ('qty_unit', models.IntegerField(default=0)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='core.entitas')),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='core.grupbahan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='master.masterproduk')),
            ],
            options={
                'verbose_name_plural': 'Stok barang jadi',
                'db_table': 'inventory_stok_barang_jadi',
                'ordering': ['entitas', 'item', 'kemasan'],
                'constraints': [models.UniqueConstraint(fields=('entitas', 'grup_bahan', 'item', 'kemasan'), name='uq_stok_jadi_posisi'), models.CheckConstraint(condition=models.Q(('qty_unit__gte', 0)), name='ck_stok_jadi_unit_non_negatif'), models.CheckConstraint(condition=models.Q(('qty_kg__gte', 0)), name='ck_stok_jadi_kg_non_negatif')],
            },
        ),
        migrations.CreateModel(
            name='StokItemsPabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_per_kemasan', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_kemasan', models.IntegerField(default=0)),
                ('total_isi', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_items_pabrik', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Stok items pabrik',
                'db_table': 'warehouse_stok_items_pabrik',
                'ordering': ['produk', 'isi_per_kemasan'],
                'constraints': [models.UniqueConstraint(fields=('produk', 'isi_per_kemasan'), name='uq_stok_items_pabrik_posisi'), models.CheckConstraint(condition=models.Q(('qty_kemasan__gte', 0)), name='ck_stok_items_pabrik_non_negatif')],
            },
        ),
    ]
