# Generated by Django 5.2.10 on 2026-08-01 07:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunting', '0005_seed_coa'),
        ('dokumen', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanSelisih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('jenis', models.CharField(choices=[('KURANG_KIRIM', 'Kurang kirim'), ('LEBIH_KIRIM', 'Lebih kirim'), ('BERAT_KURANG', 'Berat kurang dari label'), ('RUSAK', 'Barang rusak'), ('SALAH_BARANG', 'Barang tidak sesuai pesanan'), ('MUTU', 'Mutu tidak sesuai')], db_index=True, max_length=14)),
                ('status', models.CharField(choices=[('DIBUKA', 'Dibuka'), ('DIAJUKAN', 'Diajukan ke suplier'), ('DISEPAKATI', 'Disepakati suplier'), ('DISELESAIKAN', 'Selesai'), ('DITUTUP', 'Ditutup tanpa klaim')], db_index=True, default='DIBUKA', max_length=14)),
                ('qty_selisih', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('nilai_selisih', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('uraian', models.TextField()),
                ('resolusi', models.CharField(blank=True, choices=[('TERIMA', 'Terima apa adanya'), ('POTONG', 'Potong tagihan'), ('SUSULAN', 'Suplier kirim susulan'), ('RETUR', 'Retur ke suplier'), ('GANTI', 'Ganti barang')], max_length=8)),
                ('nilai_klaim', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('catatan_resolusi', models.TextField(blank=True)),
                ('diselesaikan_pada', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Laporan selisih',
                'db_table': 'warehouse_laporan_selisih',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.AddField(
            model_name='penerimaanbarang',
            name='ada_selisih',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='penerimaanbarang',
            name='nama_sopir',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='penerimaanbarang',
            name='no_kendaraan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='penerimaanitem',
            name='isi_per_koli',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Isi nominal tiap koli menurut label.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='penerimaanitem',
            name='jenis_kemasan',
            field=models.CharField(choices=[('KARUNG', 'Karung'), ('DRUM', 'Drum'), ('JERIGEN', 'Jerigen'), ('DUS', 'Dus'), ('SAK', 'Sak'), ('CURAH', 'Curah / tanpa kemasan')], default='CURAH', max_length=8),
        ),
        migrations.AddField(
            model_name='penerimaanitem',
            name='jumlah_koli',
            field=models.PositiveIntegerField(blank=True, help_text='Jumlah karung/drum/dus. Kosongkan untuk curah.', null=True),
        ),
        migrations.AddField(
            model_name='penerimaanitem',
            name='qty_deklarasi',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='penerimaanitem',
            name='qty_diterima',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='penerimaanbarang',
            index=models.Index(fields=['ada_selisih'], name='ix_penerimaan_selisih'),
        ),
        migrations.AddConstraint(
            model_name='penerimaanitem',
            constraint=models.CheckConstraint(condition=models.Q(('isi_per_koli__isnull', True), ('isi_per_koli__gt', 0), _connector='OR'), name='ck_penerimaan_isi_positif'),
        ),
        migrations.AddField(
            model_name='laporanselisih',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporanselisih',
            name='diselesaikan_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selisih_diselesaikan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporanselisih',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumen.lampiran'),
        ),
        migrations.AddField(
            model_name='laporanselisih',
            name='penerimaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_selisih', to='warehouse.penerimaanbarang'),
        ),
        migrations.AddField(
            model_name='laporanselisih',
            name='penerimaan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laporan_selisih', to='warehouse.penerimaanitem'),
        ),
        migrations.AddIndex(
            model_name='laporanselisih',
            index=models.Index(fields=['status', '-tanggal'], name='ix_selisih_status'),
        ),
        migrations.AddConstraint(
            model_name='laporanselisih',
            constraint=models.UniqueConstraint(fields=('nomor',), name='uq_selisih_nomor'),
        ),
        migrations.AddConstraint(
            model_name='laporanselisih',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_klaim__gte', 0)), name='ck_selisih_klaim_nonneg'),
        ),
    ]
