# Generated by Django 5.2.10 on 2026-08-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_laporanselisih_penerimaanbarang_ada_selisih_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penerimaanbarang',
            name='nama_sopir',
        ),
        migrations.RemoveField(
            model_name='penerimaanbarang',
            name='no_kendaraan',
        ),
    ]
