# Generated by Django 5.2.10 on 2026-08-09 02:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_kategori_kode_alter_pelanggan_kode_and_more'),
        ('warehouse', '0003_remove_penerimaanbarang_nama_sopir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_do', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('pengemudi', models.CharField(blank=True, max_length=100)),
                ('plat_nomor', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'tx_delivery_order',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='warehouse.deliveryorder')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.produk')),
            ],
            options={
                'db_table': 'tx_delivery_order_item',
            },
        ),
    ]
