# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(blank=True, max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'db_table': 'master_kategori',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(blank=True, max_length=16, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('kontak_nama', models.CharField(blank=True, max_length=120)),
                ('kontak_hp', models.CharField(blank=True, max_length=20)),
                ('termin_hari_default', models.PositiveSmallIntegerField(default=0)),
                ('plafon_kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pelanggan',
                'db_table': 'master_pelanggan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=8, unique=True)),
                ('nama', models.CharField(max_length=40)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Satuan',
                'db_table': 'master_satuan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(blank=True, max_length=16, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('kontak_nama', models.CharField(blank=True, max_length=120)),
                ('kontak_hp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('termin_hari_default', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Suplier',
                'db_table': 'master_suplier',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(blank=True, max_length=24, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('BAHAN_BAKU', 'Bahan baku'), ('BARANG_JADI', 'Barang jadi'), ('KEMASAN', 'Kemasan'), ('LAIN', 'Lain-lain')], db_index=True, max_length=12)),
                ('lokasi_simpan', models.CharField(blank=True, max_length=100)),
                ('disimpan_di_tanki', models.BooleanField(default=False)),
                ('aktif', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='master.kategori')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='master.satuan')),
                ('suplier', models.ManyToManyField(blank=True, related_name='produk_disuplai', to='master.suplier')),
            ],
            options={
                'verbose_name_plural': 'Produk',
                'db_table': 'master_produk',
                'ordering': ['kode'],
                'indexes': [models.Index(fields=['jenis', 'aktif'], name='ix_produk_jenis_aktif')],
            },
        ),
    ]
