# Generated by Django 5.2.10 on 2026-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='lokasi_simpan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produk',
            name='suplier',
            field=models.ManyToManyField(blank=True, related_name='produk_disuplai', to='master.suplier'),
        ),
        migrations.AddField(
            model_name='satuan',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
