# Generated by Django 5.2.10 on 2026-08-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_kategori_aktif_produk_lokasi_simpan_produk_suplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='kode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kode',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='kode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
