# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('SETOR', 'Setoran (pembelian raw)'), ('TARIK', 'Penarikan (packing barang jadi)'), ('RUGI', 'Beban susut produksi'), ('PENYESUAIAN', 'Penyesuaian manual')], max_length=14)),
                ('arah', models.SmallIntegerField()),
                ('qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('waktu', models.DateTimeField(db_index=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mutasi klaim',
                'db_table': 'inventory_mutasi_klaim',
                'ordering': ['waktu', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=48, unique=True)),
                ('total_unit', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga_per_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('nilai_hpp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('menghabiskan', models.BooleanField(default=False)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('waktu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Diposting'), ('VOID', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Packing',
                'db_table': 'inventory_packing',
                'ordering': ['-waktu', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=48, unique=True)),
                ('no_po', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga_per_kg', models.DecimalField(decimal_places=6, max_digits=20)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateField(db_index=True)),
                ('waktu', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Diposting'), ('VOID', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10)),
                ('sumber', models.CharField(choices=[('PENERIMAAN', 'Dari penerimaan gudang'), ('MANUAL', 'Input manual (saldo awal / koreksi)')], db_index=True, default='MANUAL', max_length=12)),
                ('catatan', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pembelian',
                'db_table': 'inventory_pembelian',
                'ordering': ['-waktu', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEntitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('total_setor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_tarik', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_rugi', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('qty_setor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('qty_tarik', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Saldo entitas',
                'db_table': 'inventory_saldo_entitas',
            },
        ),
        migrations.CreateModel(
            name='RawMutasiEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Saldo pool',
                'db_table': 'inventory_raw_mutasi_entity',
                'ordering': ['grup_bahan', 'produk'],
            },
        ),
        migrations.CreateModel(
            name='Kemasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=40, unique=True)),
                ('bobot_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kemasan',
                'db_table': 'inventory_kemasan',
                'ordering': ['nama'],
                'constraints': [models.CheckConstraint(condition=models.Q(('bobot_kg__gt', 0)), name='ck_kemasan_bobot_positif')],
            },
        ),
    ]
