# Generated by Django 5.2.10 on 2026-08-01 07:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_seed_entitas'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tangki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('kapasitas_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('isi_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('aktif', models.BooleanField(default=True)),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tangki', to='core.grupbahan')),
                ('produk_terisi', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Tangki',
                'db_table': 'inventory_tangki',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('lapis', models.CharField(choices=[('RAW', 'Bahan bertuan'), ('POOL', 'Pool produksi'), ('JADI', 'Barang jadi')], db_index=True, max_length=4)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('urutan_terakhir', models.BigIntegerField(default=0, editable=False)),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok', to='core.grupbahan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok', to='master.produk')),
                ('tangki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok', to='inventory.tangki')),
            ],
            options={
                'verbose_name_plural': 'Stok',
                'db_table': 'inventory_stok',
                'ordering': ['lapis', 'produk__kode'],
            },
        ),
        migrations.CreateModel(
            name='MutasiKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jenis', models.CharField(choices=[('SETOR', 'Setor bahan ke pool'), ('AMBIL', 'Klaim barang jadi'), ('KOREKSI', 'Koreksi'), ('LUNAS', 'Penyelesaian antar entitas')], max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('tarif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=96, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klaim', to='core.entitas')),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klaim', to='core.grupbahan')),
                ('produk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='klaim', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Mutasi klaim',
                'db_table': 'inventory_mutasi_klaim',
                'ordering': ['grup_bahan', 'tanggal', 'id'],
                'indexes': [models.Index(fields=['grup_bahan', 'entitas', 'tanggal'], name='ix_klaim_grup_ent')],
            },
        ),
        migrations.CreateModel(
            name='NilaiEkuivalen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nilai_per_satuan', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('berlaku_sejak', models.DateField()),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nilai_ekuivalen', to='master.produk')),
            ],
            options={
                'verbose_name_plural': 'Nilai ekuivalen',
                'db_table': 'inventory_nilai_ekuivalen',
                'ordering': ['produk__kode', '-berlaku_sejak'],
                'constraints': [models.UniqueConstraint(fields=('produk', 'berlaku_sejak'), name='uq_ekuivalen_produk_tanggal')],
            },
        ),
        migrations.CreateModel(
            name='PosisiKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('total_setor', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('total_ambil', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('nilai_bersih', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posisi_klaim', to='core.entitas')),
                ('grup_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posisi_klaim', to='core.grupbahan')),
            ],
            options={
                'verbose_name_plural': 'Posisi klaim',
                'db_table': 'inventory_posisi_klaim',
                'ordering': ['grup_bahan', 'entitas__kode'],
                'constraints': [models.UniqueConstraint(fields=('entitas', 'grup_bahan'), name='uq_posisi_klaim')],
            },
        ),
        migrations.CreateModel(
            name='SaldoEntitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('nilai', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_bahan', to='core.entitas')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kepemilikan', to='inventory.stok')),
            ],
            options={
                'verbose_name_plural': 'Saldo entitas',
                'db_table': 'inventory_saldo_entitas',
                'ordering': ['stok', 'entitas__kode'],
                'constraints': [models.UniqueConstraint(fields=('stok', 'entitas'), name='uq_saldo_entitas'), models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='ck_saldo_entitas_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='MutasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.BigIntegerField()),
                ('tanggal', models.DateTimeField(db_index=True)),
                ('jenis', models.CharField(choices=[('TERIMA', 'Penerimaan barang'), ('SETOR', 'Setor ke pool'), ('PAKAI', 'Pemakaian produksi'), ('HASIL', 'Hasil produksi'), ('KLAIM', 'Klaim barang jadi'), ('KIRIM', 'Pengiriman'), ('RETUR', 'Retur'), ('OPNAME', 'Penyesuaian opname'), ('SUSUT', 'Susut / penguapan')], max_length=8)),
                ('masuk', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('keluar', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('saldo_akhir', models.DecimalField(decimal_places=3, max_digits=14)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=96, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi', to='inventory.stok')),
            ],
            options={
                'verbose_name_plural': 'Mutasi stok',
                'db_table': 'inventory_mutasi_stok',
                'ordering': ['stok', 'urutan'],
                'indexes': [models.Index(fields=['stok', '-urutan'], name='ix_mutasi_stok_urut')],
                'constraints': [models.UniqueConstraint(fields=('stok', 'urutan'), name='uq_mutasi_stok_urutan'), models.CheckConstraint(condition=models.Q(('masuk__gte', 0), ('keluar__gte', 0)), name='ck_mutasi_stok_nonneg'), models.CheckConstraint(condition=models.Q(('masuk', 0), ('keluar', 0), _connector='OR'), name='ck_mutasi_stok_satu_sisi')],
            },
        ),
        migrations.AddConstraint(
            model_name='tangki',
            constraint=models.CheckConstraint(condition=models.Q(('kapasitas_kg__gt', 0)), name='ck_tangki_kapasitas'),
        ),
        migrations.AddConstraint(
            model_name='tangki',
            constraint=models.CheckConstraint(condition=models.Q(('isi_kg__gte', 0), ('isi_kg__lte', models.F('kapasitas_kg'))), name='ck_tangki_isi_dalam_kapasitas'),
        ),
        migrations.AddIndex(
            model_name='stok',
            index=models.Index(fields=['grup_bahan', 'lapis'], name='ix_stok_grup_lapis'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.UniqueConstraint(condition=models.Q(('tangki__isnull', False)), fields=('produk', 'grup_bahan', 'lapis', 'tangki'), name='uq_stok_tangki'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.UniqueConstraint(condition=models.Q(('tangki__isnull', True)), fields=('produk', 'grup_bahan', 'lapis'), name='uq_stok_rak'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='ck_stok_nonneg'),
        ),
    ]