# Generated by Django 5.2.10 on 2026-08-12 16:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_entitas'),
        ('inventory', '0001_initial'),
        ('master', '0003_alter_kategori_kode_alter_pelanggan_kode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kemasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('isi', models.DecimalField(decimal_places=3, help_text='Curah yang habis untuk satu unit kemasan.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kemasan',
                'db_table': 'inventory_kemasan',
                'ordering': ['produk_curah__kode', 'isi'],
            },
        ),
        migrations.AddField(
            model_name='mutasistok',
            name='nilai_keluar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='mutasistok',
            name='nilai_masuk',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='mutasistok',
            name='saldo_nilai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='posisiklaim',
            name='total_rugi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='stok',
            name='nilai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mutasiklaim',
            name='jenis',
            field=models.CharField(choices=[('SETOR', 'Setor bahan ke pool'), ('AMBIL', 'Klaim barang jadi'), ('RUGI', 'Pembebanan kerugian pool'), ('KOREKSI', 'Koreksi'), ('LUNAS', 'Penyelesaian antar entitas')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='mutasistok',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_masuk__gte', 0), ('nilai_keluar__gte', 0)), name='ck_mutasi_nilai_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='mutasistok',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_masuk', 0), ('nilai_keluar', 0), _connector='OR'), name='ck_mutasi_nilai_satu_sisi'),
        ),
        migrations.AddConstraint(
            model_name='saldoentitas',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('nilai', 0), _connector='OR'), name='ck_saldo_kosong_tanpa_nilai'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_stok_nilai_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('nilai', 0), _connector='OR'), name='ck_stok_kosong_tanpa_nilai'),
        ),
        migrations.AddField(
            model_name='kemasan',
            name='produk_curah',
            field=models.ForeignKey(help_text='Produk yang tersimpan di tangki, satuan curah.', on_delete=django.db.models.deletion.PROTECT, related_name='kemasan', to='master.produk'),
        ),
        migrations.AddField(
            model_name='kemasan',
            name='produk_kemasan',
            field=models.ForeignKey(help_text='Produk yang keluar setelah dikemas, satuan jual.', on_delete=django.db.models.deletion.PROTECT, related_name='dari_curah', to='master.produk'),
        ),
        migrations.AddConstraint(
            model_name='kemasan',
            constraint=models.UniqueConstraint(fields=('produk_curah', 'produk_kemasan'), name='uq_kemasan_pasangan'),
        ),
        migrations.AddConstraint(
            model_name='kemasan',
            constraint=models.CheckConstraint(condition=models.Q(('isi__gt', 0)), name='ck_kemasan_isi'),
        ),
    ]
