# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
        ('produksi', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mutasiklaim',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutasiklaim',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_klaim', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='mutasiklaim',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_klaim', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='packing',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_set', to='produksi.batch'),
        ),
        migrations.AddField(
            model_name='packing',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packing',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='packing',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='inventory.kemasan'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembelian_pool', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembelian_pool', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='penerimaan_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pembelian', to='warehouse.penerimaanitem'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembelian_pool', to='master.produk'),
        ),
        migrations.AddField(
            model_name='saldoentitas',
            name='entitas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_klaim', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='saldopool',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_pool', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='saldopool',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_pool', to='master.produk'),
        ),
        migrations.AddIndex(
            model_name='mutasiklaim',
            index=models.Index(fields=['entitas', 'waktu', 'id'], name='ix_mutasi_entitas'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.UniqueConstraint(fields=('ref_type', 'ref_id', 'tipe', 'entitas'), name='uq_mutasi_idempoten'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.CheckConstraint(condition=models.Q(('arah__in', [-1, 1])), name='ck_mutasi_arah_valid'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_mutasi_nilai_non_negatif'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['batch', 'status'], name='ix_pack_batch'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['entitas', 'waktu'], name='ix_pack_entitas'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_pack_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('total_unit__gt', 0)), name='ck_pack_unit_positif'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_hpp__gte', 0)), name='ck_pack_nilai_non_negatif'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['entitas', 'waktu'], name='ix_beli_entitas'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['tanggal', 'status'], name='ix_beli_tanggal'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_beli_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('harga_per_kg__gte', 0)), name='ck_beli_harga_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_beli_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sumber', 'PENERIMAAN'), _negated=True), ('penerimaan_item__isnull', False), _connector='OR'), name='ck_beli_penerimaan_ada_jejak'),
        ),
        migrations.AddConstraint(
            model_name='saldopool',
            constraint=models.UniqueConstraint(fields=('grup_bahan', 'produk'), name='inv_pool_unik_per_grup'),
        ),
        migrations.AddConstraint(
            model_name='saldopool',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gte', 0)), name='inv_pool_qty_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='saldopool',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='inv_pool_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='saldopool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_kg', 0), _negated=True), ('nilai', 0), _connector='OR'), name='inv_pool_kosong_tanpa_nilai'),
        ),
    ]
