# Generated by Django 5.2.10 on 2026-09-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='penerimaan_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pembelian', to='warehouse.penerimaanitem'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembelian_pool', to='master.produk'),
        ),
        migrations.AddField(
            model_name='poolkemasan',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_kemasan', to='master.produk'),
        ),
        migrations.AddField(
            model_name='packing',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='inventory.poolkemasan'),
        ),
        migrations.AddField(
            model_name='poolresource',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_resource', to='master.produk'),
        ),
        migrations.AddField(
            model_name='saldoentitas',
            name='entitas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_klaim', to='core.entitas'),
        ),
        migrations.AddIndex(
            model_name='mutasiklaim',
            index=models.Index(fields=['entitas', 'waktu', 'id'], name='ix_mutasi_entitas'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.UniqueConstraint(fields=('ref_type', 'ref_id', 'tipe', 'entitas'), name='uq_mutasi_idempoten'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.CheckConstraint(condition=models.Q(('arah__in', [-1, 1])), name='ck_mutasi_arah_valid'),
        ),
        migrations.AddConstraint(
            model_name='mutasiklaim',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_mutasi_nilai_non_negatif'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['entitas', 'waktu'], name='ix_beli_entitas'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['tanggal', 'status'], name='ix_beli_tanggal'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_beli_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('harga_per_kg__gte', 0)), name='ck_beli_harga_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_beli_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='pembelian',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sumber', 'PENERIMAAN'), _negated=True), ('penerimaan_item__isnull', False), _connector='OR'), name='ck_beli_penerimaan_ada_jejak'),
        ),
        migrations.AddConstraint(
            model_name='poolkemasan',
            constraint=models.UniqueConstraint(fields=('produk',), name='inv_pool_kms_unik_per_produk'),
        ),
        migrations.AddConstraint(
            model_name='poolkemasan',
            constraint=models.CheckConstraint(condition=models.Q(('qty_unit__gte', 0)), name='inv_pool_kms_qty_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='poolkemasan',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='inv_pool_kms_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='poolkemasan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_unit', 0), _negated=True), ('nilai', 0), _connector='OR'), name='inv_pool_kms_kosong_tanpa_nilai'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['batch', 'status'], name='ix_pack_batch'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['entitas', 'waktu'], name='ix_pack_entitas'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['nama_hasil', 'status'], name='ix_pack_hasil'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gt', 0)), name='ck_pack_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('total_unit__gt', 0)), name='ck_pack_unit_positif'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('cost_nom__gte', 0)), name='ck_pack_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='poolresource',
            constraint=models.UniqueConstraint(fields=('produk',), name='inv_pool_res_unik_per_produk'),
        ),
        migrations.AddConstraint(
            model_name='poolresource',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gte', 0)), name='inv_pool_res_qty_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='poolresource',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='inv_pool_res_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='poolresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_kg', 0), _negated=True), ('nilai', 0), _connector='OR'), name='inv_pool_res_kosong_tanpa_nilai'),
        ),
    ]
