flowchart LR
    subgraph sg_v_WorkOrderViewSet["WorkOrderViewSet"]
        direction LR
        u_WorkOrderViewSet_0[/"/api/v1/work-order/^$"/]
        u_WorkOrderViewSet_0 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_1[/"/api/v1/work-order/^\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_1 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_2[/"/api/v1/work-order/^mading/$"/]
        u_WorkOrderViewSet_2 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_3[/"/api/v1/work-order/^mading\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_3 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_4[/"/api/v1/work-order/^staff/$"/]
        u_WorkOrderViewSet_4 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_5[/"/api/v1/work-order/^staff\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_5 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_6[/"/api/v1/work-order/^?Ppk^/.+/$"/]
        u_WorkOrderViewSet_6 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_7[/"/api/v1/work-order/^?Ppk^/.+\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_7 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_8[/"/api/v1/work-order/^?Ppk^/.+/approve/$"/]
        u_WorkOrderViewSet_8 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_9[/"/api/v1/work-order/^?Ppk^/.+/approve\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_9 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_10[/"/api/v1/work-order/^?Ppk^/.+/kirim_pesan/$"/]
        u_WorkOrderViewSet_10 --> v_WorkOrderViewSet
        u_WorkOrderViewSet_11[/"/api/v1/work-order/^?Ppk^/.+/kirim_pesan\.?Pformata-z0-9+/?$"/]
        u_WorkOrderViewSet_11 --> v_WorkOrderViewSet
        v_WorkOrderViewSet["WorkOrderViewSet<br/>IsAuthenticated, CanAksesWorkOrder<br/>TANPA atomic"]
        s_WorkOrderSerializer["WorkOrderSerializer"]
        v_WorkOrderViewSet --> s_WorkOrderSerializer
        m_WorkOrder[("WorkOrder")]
        s_WorkOrderSerializer --> m_WorkOrder
    end

    classDef bahaya fill:#FCEBEB,stroke:#A32D2D,color:#501313
    classDef awas fill:#FAEEDA,stroke:#854F0B,color:#412402
    class v_WorkOrderViewSet awas
