# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiTerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='logistik/bukti/%Y/%m/')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('idem_key', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'db_table': 'logistik_bukti_terima',
                'ordering': ['perhentian', 'waktu'],
            },
        ),
        migrations.CreateModel(
            name='JejakPosisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('akurasi_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'logistik_jejak_posisi',
                'ordering': ['pengiriman', 'waktu'],
            },
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('plat_nomor', models.CharField(blank=True, max_length=16)),
                ('kapasitas_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kendaraan',
                'db_table': 'logistik_kendaraan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DISIAPKAN', 'Disiapkan'), ('BERANGKAT', 'Berangkat'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], db_index=True, default='DISIAPKAN', max_length=12)),
                ('waktu_berangkat', models.DateTimeField(blank=True, editable=False, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, editable=False, null=True)),
                ('jarak_total_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('ongkos_perkiraan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'logistik_pengiriman',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Perhentian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribusi_id', models.PositiveIntegerField(db_index=True)),
                ('nomor_distribusi', models.CharField(blank=True, max_length=32)),
                ('pelanggan_nama', models.CharField(blank=True, max_length=200)),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('urutan_usulan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('jarak_dari_sebelum_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('estimasi_menit', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('SAMPAI', 'Sampai di lokasi'), ('DITERIMA', 'Diterima'), ('DIRETUR', 'Diretur')], db_index=True, default='MENUNGGU', max_length=10)),
                ('waktu_sampai', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'logistik_perhentian',
                'ordering': ['pengiriman', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='logistik/retur/%Y/%m/')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('disetujui_pada', models.DateTimeField(blank=True, null=True)),
                ('stok_dikembalikan', models.BooleanField(default=False)),
                ('idem_key', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'db_table': 'logistik_retur',
                'ordering': ['-dicatat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TarifOngkos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('berlaku_sejak', models.DateField(default=django.utils.timezone.localdate)),
                ('tarif_per_km', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('biaya_tetap', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name_plural': 'Tarif ongkos',
                'db_table': 'logistik_tarif_ongkos',
                'ordering': ['-berlaku_sejak'],
            },
        ),
    ]
