# Generated by Django 5.2.10 on 2026-08-07 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_seed_entitas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('plat_nomor', models.CharField(blank=True, max_length=16)),
                ('kapasitas_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kendaraan',
                'db_table': 'logistik_kendaraan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='TarifOngkos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('berlaku_sejak', models.DateField(default=django.utils.timezone.localdate)),
                ('tarif_per_km', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('biaya_tetap', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name_plural': 'Tarif ongkos',
                'db_table': 'logistik_tarif_ongkos',
                'ordering': ['-berlaku_sejak'],
            },
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(editable=False, max_length=32)),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DISIAPKAN', 'Disiapkan'), ('BERANGKAT', 'Berangkat'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], db_index=True, default='DISIAPKAN', max_length=12)),
                ('waktu_berangkat', models.DateTimeField(blank=True, editable=False, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, editable=False, null=True)),
                ('jarak_total_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('ongkos_perkiraan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman', to='core.entitas')),
                ('kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman', to='logistik.kendaraan')),
                ('kurir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman_dibawa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logistik_pengiriman',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JejakPosisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('akurasi_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jejak', to='logistik.pengiriman')),
            ],
            options={
                'db_table': 'logistik_jejak_posisi',
                'ordering': ['pengiriman', 'waktu'],
            },
        ),
        migrations.CreateModel(
            name='Perhentian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribusi_id', models.PositiveIntegerField(db_index=True)),
                ('nomor_distribusi', models.CharField(blank=True, max_length=32)),
                ('pelanggan_nama', models.CharField(blank=True, max_length=200)),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('urutan_usulan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('jarak_dari_sebelum_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('estimasi_menit', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('SAMPAI', 'Sampai di lokasi'), ('DITERIMA', 'Diterima'), ('DIRETUR', 'Diretur')], db_index=True, default='MENUNGGU', max_length=10)),
                ('waktu_sampai', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perhentian', to='logistik.pengiriman')),
            ],
            options={
                'db_table': 'logistik_perhentian',
                'ordering': ['pengiriman', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='BuktiTerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='logistik/bukti/%Y/%m/')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('idem_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('diunggah_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bukti_terima_diunggah', to=settings.AUTH_USER_MODEL)),
                ('perhentian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bukti', to='logistik.perhentian')),
            ],
            options={
                'db_table': 'logistik_bukti_terima',
                'ordering': ['perhentian', 'waktu'],
            },
        ),
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='logistik/retur/%Y/%m/')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('disetujui_pada', models.DateTimeField(blank=True, null=True)),
                ('stok_dikembalikan', models.BooleanField(default=False)),
                ('idem_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('dicatat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retur_dicatat', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_disetujui', to=settings.AUTH_USER_MODEL)),
                ('perhentian', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retur', to='logistik.perhentian')),
            ],
            options={
                'db_table': 'logistik_retur',
                'ordering': ['-dicatat_pada'],
            },
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['kurir', 'status', '-tanggal'], name='ix_kirim_kurir_status'),
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['status', '-tanggal'], name='ix_kirim_status'),
        ),
        migrations.AddConstraint(
            model_name='pengiriman',
            constraint=models.UniqueConstraint(fields=('entitas', 'nomor'), name='uq_pengiriman_nomor'),
        ),
        migrations.AddIndex(
            model_name='jejakposisi',
            index=models.Index(fields=['pengiriman', 'waktu'], name='ix_jejak_kirim'),
        ),
        migrations.AddConstraint(
            model_name='perhentian',
            constraint=models.UniqueConstraint(fields=('pengiriman', 'distribusi_id'), name='uq_perhentian_distribusi'),
        ),
        migrations.AddConstraint(
            model_name='buktiterima',
            constraint=models.UniqueConstraint(condition=models.Q(('idem_key', ''), _negated=True), fields=('idem_key',), name='uq_bukti_idem'),
        ),
        migrations.AddConstraint(
            model_name='retur',
            constraint=models.UniqueConstraint(condition=models.Q(('idem_key', ''), _negated=True), fields=('idem_key',), name='uq_retur_idem'),
        ),
    ]
