# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('logistik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buktiterima',
            name='diunggah_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bukti_terima_diunggah', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='kendaraan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman', to='logistik.kendaraan'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='kurir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengiriman_dibawa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jejakposisi',
            name='pengiriman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jejak', to='logistik.pengiriman'),
        ),
        migrations.AddField(
            model_name='perhentian',
            name='pengiriman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perhentian', to='logistik.pengiriman'),
        ),
        migrations.AddField(
            model_name='buktiterima',
            name='perhentian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bukti', to='logistik.perhentian'),
        ),
        migrations.AddField(
            model_name='retur',
            name='dicatat_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retur_dicatat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retur',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retur_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retur',
            name='perhentian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retur', to='logistik.perhentian'),
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['kurir', 'status', '-tanggal'], name='ix_kirim_kurir_status'),
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['status', '-tanggal'], name='ix_kirim_status'),
        ),
        migrations.AddConstraint(
            model_name='pengiriman',
            constraint=models.UniqueConstraint(fields=('entitas', 'nomor'), name='uq_pengiriman_nomor'),
        ),
        migrations.AddIndex(
            model_name='jejakposisi',
            index=models.Index(fields=['pengiriman', 'waktu'], name='ix_jejak_kirim'),
        ),
        migrations.AddConstraint(
            model_name='perhentian',
            constraint=models.UniqueConstraint(fields=('pengiriman', 'distribusi_id'), name='uq_perhentian_distribusi'),
        ),
        migrations.AddConstraint(
            model_name='buktiterima',
            constraint=models.UniqueConstraint(condition=models.Q(('idem_key', ''), _negated=True), fields=('idem_key',), name='uq_bukti_idem'),
        ),
        migrations.AddConstraint(
            model_name='retur',
            constraint=models.UniqueConstraint(condition=models.Q(('idem_key', ''), _negated=True), fields=('idem_key',), name='uq_retur_idem'),
        ),
    ]
