# Generated by Django 5.2.10 on 2026-08-01 01:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0002_initial'),
        ('core', '0002_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekeningBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(choices=[('BANK', 'Rekening bank'), ('KAS', 'Kas tunai'), ('KAS_KECIL', 'Kas kecil')], max_length=10)),
                ('nama_bank', models.CharField(blank=True, max_length=80)),
                ('nomor_rekening', models.CharField(blank=True, max_length=40)),
                ('nama_pemilik', models.CharField(blank=True, max_length=120)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=18)),
                ('urutan_terakhir', models.BigIntegerField(default=0, editable=False)),
                ('aktif', models.BooleanField(default=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekening', to='akunting.akun')),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekening', to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'Rekening bank',
                'db_table': 'keuangan_rekening_bank',
                'ordering': ['entitas__kode', 'nama_bank'],
            },
        ),
        migrations.CreateModel(
            name='MutasiKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.BigIntegerField()),
                ('tanggal', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('saldo_akhir', models.DecimalField(decimal_places=2, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('referensi', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=96, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi', to='keuangan.rekeningbank')),
            ],
            options={
                'verbose_name_plural': 'Mutasi kas',
                'db_table': 'keuangan_mutasi_kas',
                'ordering': ['rekening', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='RencanaBayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('tanggal_rencana', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('DISETUJUI', 'Disetujui'), ('DIEKSEKUSI', 'Sudah dibayar'), ('DITOLAK', 'Ditolak')], db_index=True, default='DRAFT', max_length=12)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dieksekusi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana_dieksekusi', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana_disetujui', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas')),
                ('mutasi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana', to='keuangan.mutasikas')),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencana_bayar', to='keuangan.rekeningbank')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencana_bayar', to='master.suplier')),
            ],
            options={
                'verbose_name_plural': 'Rencana bayar',
                'db_table': 'keuangan_rencana_bayar',
                'ordering': ['tanggal_rencana', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rekeningbank',
            constraint=models.UniqueConstraint(condition=models.Q(('nomor_rekening', ''), _negated=True), fields=('entitas', 'nomor_rekening'), name='uq_rekening_nomor'),
        ),
        migrations.AddIndex(
            model_name='mutasikas',
            index=models.Index(fields=['rekening', '-urutan'], name='ix_mutasi_kas_urut'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.UniqueConstraint(fields=('rekening', 'urutan'), name='uq_mutasi_kas_urutan'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_mutasi_kas_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_mutasi_kas_satu_sisi'),
        ),
        migrations.AddIndex(
            model_name='rencanabayar',
            index=models.Index(fields=['status', 'tanggal_rencana'], name='ix_rencana_status'),
        ),
    ]
