# Generated by Django 5.2.10 on 2026-08-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_entitas'),
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengeluaranKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=255)),
                ('pemohon', models.CharField(max_length=120)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bukti_nota', models.FileField(blank=True, null=True, upload_to='keuangan/nota/')),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas')),
                ('mutasi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengeluaran', to='keuangan.mutasikas')),
            ],
            options={
                'db_table': 'keuangan_pengeluaran_kas',
                'ordering': ['-id'],
            },
        ),
    ]
