# Generated by Django 5.2.10 on 2026-08-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('keuangan', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanabayar',
            name='dibuat_oleh',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='dieksekusi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana_dieksekusi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entitas'),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='mutasi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencana', to='keuangan.mutasikas'),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='rekening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencana_bayar', to='keuangan.rekeningbank'),
        ),
        migrations.AddField(
            model_name='rencanabayar',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencana_bayar', to='master.suplier'),
        ),
        migrations.AddConstraint(
            model_name='rekeningbank',
            constraint=models.UniqueConstraint(condition=models.Q(('nomor_rekening', ''), _negated=True), fields=('entitas', 'nomor_rekening'), name='uq_rekening_nomor'),
        ),
        migrations.AddIndex(
            model_name='mutasikas',
            index=models.Index(fields=['rekening', '-urutan'], name='ix_mutasi_kas_urut'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.UniqueConstraint(fields=('rekening', 'urutan'), name='uq_mutasi_kas_urutan'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('kredit__gte', 0)), name='ck_mutasi_kas_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='mutasikas',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('kredit', 0), _connector='OR'), name='ck_mutasi_kas_satu_sisi'),
        ),
        migrations.AddIndex(
            model_name='rencanabayar',
            index=models.Index(fields=['status', 'tanggal_rencana'], name='ix_rencana_status'),
        ),
    ]
